# utils/config.py
# Auto-generated by 01_setup_and_environment.ipynb
# These IDs are confirmed against StatsBomb Open Data.

# Competition IDs
WC2022_COMPETITION_ID   = 43
WC2022_SEASON_ID        = 106

EURO2024_COMPETITION_ID = 55
EURO2024_SEASON_ID      = 282

# Paths
OUTPUTS_DATA_DIR    = "../outputs/data"
OUTPUTS_FIGURES_DIR = "../outputs/figures"

# Tournament labels (for plots and file names)
TOURNAMENT_LABELS = {
    "WC2022"   : "FIFA World Cup 2022",
    "EURO2024" : "UEFA Euro 2024",
}
